export const tools = [
    {
        "alias": "AdonisJS",
        "fullName": "AdonisJS",
        "src": "adonis",
        "type": "framework",
        "area": "web",
        "stack": "back-end",
        "status": null,
        "associated": ["JavaScript","Node.js"],
        "about": "Framework back-end, em JavaScript, para construção de servidores web.",
        "start": null,
        "advance": null
    },
    {
        "alias": "AngularJS",
        "fullName": "AngularJS",
        "src": "angularjs",
        "type": "framework",
        "area": "web",
        "stack": "front-end",
        "status": null,
        "associated": ["JavaScript","Google", "MVC"],
        "about": "Framework front-end, em JavaScript, para desenvolvimento web.",
        "start": null,
        "advance": null
    },
    {
        "alias": "Apache",
        "fullName": "Apache HTTP Server",
        "src": "apache",
        "type": "server",
        "area": "web",
        "stack": "back-end",
        "status": null,
        "associated": ["Apache"],
        "about": "Servidor web.",
        "start": null,
        "advance": null
    },
    {
        "alias": "Atom",
        "fullName": "Atom",
        "src": "atom",
        "type": "text-editor",
        "area": null,
        "stack": null,
        "status": null,
        "associated": ["Visual Studio Code"],
        "about": "Editor de texto.",
        "start": null,
        "advance": null
    },
    {
        "alias": "AWS",
        "fullName": "Amazon Web Services",
        "src": "aws",
        "type": "cloud",
        "area": "server",
        "stack": "back-end",
        "status": null,
        "associated": ["Amazon"],
        "about": "Plataforma para gerenciamento de dados e arquivos em nuvem.",
        "start": null,
        "advance": null
    },
    {
        "alias": "Azure",
        "fullName": "Microsoft Azure",
        "src": "azure",
        "type": "cloud",
        "area": "server",
        "stack": "back-end",
        "status": "utilizada",
        "associated": ["Microsoft"],
        "about": "Plataforma para gerenciamento de dados e arquivos em nuvem.",
        "start": "Oct 22 2021",
        "advance": null
    },
    {
        "alias": "Bootstrap",
        "fullName": "Bootstrap",
        "src": "bootstrap",
        "type": "framework",
        "area": "web",
        "stack": "front-end",
        "status": null,
        "associated": ["HTML","CSS"],
        "about": "Framework front-end para desenvolvimento de componentes web.",
        "start": null,
        "advance": null
    },
    {
        "alias": "C",
        "fullName": "C",
        "src": "c",
        "type": "programming-language",
        "area": "logic",
        "stack": null,
        "status": "utilizada",
        "associated": ["C++","C#"],
        "about": "Linguagem de programação.",
        "start": "Aug 15 2019",
        "advance": null
    },
    {
        "alias": "C++",
        "fullName": "C++",
        "src": "cplusplus",
        "type": "programming-language",
        "area": "logic",
        "stack": null,
        "status": "utilizada",
        "associated": ["C", "C#"],
        "about": "Linguagem de programação.",
        "start": "Aug 15 2020",
        "advance": null
    },
    {
        "alias": "C#",
        "fullName": "C#",
        "src": "csharp",
        "type": "programming-language",
        "area": "logic",
        "stack": null,
        "status": null,
        "associated": ["C","C++"],
        "about": "Linguagem de programação.",
        "start": null,
        "advance": null
    },
    {
        "alias": "CSS 3",
        "fullName": "Cascading Style Sheets",
        "src": "css3",
        "type": "stylesheet-language",
        "area": "web",
        "stack": "front-end",
        "status": "aprofundada",
        "associated": ["CSS", "Less", "Sass"],
        "about": "Linguagem de folhas de estilo.",
        "start": "Mar 12 2021",
        "advance": "Jul 03 2021"
    },
    {
        "alias": "Dart",
        "fullName": "Dart",
        "src": "dart",
        "type": "programming language",
        "area": "multi-platform",
        "stack": "front-end",
        "status": null,
        "associated": ["Google", "Flutter"],
        "about": "Linguagem front-end para desenvolvimento multiplataforma.",
        "start": null,
        "advance": null
    },
    {
        "alias": "Django",
        "fullName": "Django",
        "src": "django",
        "type": "framework",
        "area": "web",
        "stack": "front-end",
        "status": null,
        "associated": ["Python"],
        "about": "Framework front-end, em Python, para desenvolvimento web.",
        "start": null,
        "advance": null
    },
    {
        "alias": "Docker",
        "fullName": "Docker",
        "src": "docker",
        "type": "software",
        "area": null,
        "stack": null,
        "status": "utilizada",
        "associated": ["Docker"],
        "about": "Plataforma para virtualização.",
        "start": "Oct 11 2021",
        "advance": null
    },
    {
        "alias": ".NET Framework",
        "fullName": ".NET Framework",
        "src": "dotnet",
        "type": "software",
        "area": "multi-platform",
        "stack": null,
        "status": null,
        "associated": ["C","C++","C#","Microsoft",".NET"],
        "about": "Plataforma única para desenvolvimento de aplicações.",
        "start": null,
        "advance": null
    },
    {
        "alias": ".NET Core",
        "fullName": ".NET Core",
        "src": "dotnetcore",
        "type": "framework",
        "area": "multi-platform",
        "stack": null,
        "status": null,
        "associated": ["C","C++","C#","Microsoft",".NET"],
        "about": "Framework, em C#, para desenvolvimento de aplicações.",
        "start": null,
        "advance": null
    },
    {
        "alias": "Electron",
        "fullName": "Electron",
        "src": "electron",
        "type": "framework",
        "area": null,
        "stack": "full-stack",
        "status": null,
        "associated": ["HTML","CSS","JavaScript"],
        "about": "Framework para constução de aplicativos desktop.",
        "start": null,
        "advance": null
    },
    {
        "alias": "Expo",
        "fullName": "Expo",
        "src": "expo",
        "type": "framework",
        "area": null,
        "stack": "full-stack",
        "status": "utilizada",
        "associated": ["React","React Native"],
        "about": "Framework para aplicações React.",
        "start": "Mar 21 2021",
        "advance": null
    },
    {
        "alias": "Express",
        "fullName": "Express.js",
        "src": "express",
        "type": "framework",
        "area": "web",
        "stack": "back-end",
        "status": "utilizada",
        "associated": ["JavaScript","Node.js"],
        "about": "Framework back-end, em JavaScript, para construção de servidores web.",
        "start": "Oct 13 2021",
        "advance": null
    },
    {
        "alias": "Figma",
        "fullName": "Figma",
        "src": "figma",
        "type": "software",
        "area": null,
        "stack": null,
        "status": "utilizada",
        "associated": ["Figma"],
        "about": "Ferramenta para design de interfaces e prototipagem de projetos.",
        "start": "Aug 05 2021",
        "advance": null
    },
    {
        "alias": "Firebase",
        "fullName": "Firebase",
        "src": "firebase",
        "type": "cloud",
        "area": "database",
        "stack": "back-end",
        "status": "utilizada",
        "associated": ["Google","Google Cloud","SQL"],
        "about": "Plataforma para gerenciamento de dados e arquivos em nuvem.",
        "start": "May 11 2021",
        "advance": null
    },
    {
        "alias": "Flutter",
        "fullName": "Flutter",
        "src": "flutter",
        "type": "framework",
        "area": "multi-platform",
        "stack": "front-end",
        "status": null,
        "associated": ["Dart","Google"],
        "about": "Framework front-end, em Dart, para desenvolvimento de aplicações nativas.",
        "start": null,
        "advance": null
    },
    {
        "alias": "Git",
        "fullName": "Git",
        "src": "git",
        "type": "software",
        "area": null,
        "stack": null,
        "status": "aprofundada",
        "associated": ["GitHub","GitLab"],
        "about": "Sistema para controle de verões de arquivos.",
        "start": "Mar 15 2021",
        "advance": "Jun 30 2021"
    },
    {
        "alias": "GitHub",
        "fullName": "GitHub",
        "src": "github",
        "type": "software",
        "area": null,
        "stack": null,
        "status": "aprofundada",
        "associated": ["Git","GitLab"],
        "about": "Plataforma de hospedagem de código-fonte e arquivos com controle de versão usando o Git.",
        "start": "Mar 15 2021",
        "advance": "Jun 30 2021"
    },
    {
        "alias": "GitLab",
        "fullName": "GitLab",
        "src": "gitlab",
        "type": "software",
        "area": null,
        "stack": null,
        "status": null,
        "associated": ["Git","GitHub"],
        "about": "Gerenciador de repositórios de software baseado em git.",
        "start": null,
        "advance": null
    },
    {
        "alias": "Gitter",
        "fullName": "Gitter",
        "src": "gitter",
        "type": "software",
        "area": null,
        "stack": null,
        "status": null,
        "associated": ["Git","GitHub", "GitLab"],
        "about": "Sistema de mensagem instantânea e sala de bate-papo, para desenvolvedores e usuários de repositórios GitLab e GitHub.",
        "start": null,
        "advance": null
    },
    {
        "alias": "Go",
        "fullName": "Go",
        "src": "go",
        "type": "programming-language",
        "area": "logic",
        "stack": null,
        "status": null,
        "associated": ["Google"],
        "about": "Linguagem de programação.",
        "start": null,
        "advance": null
    },
    {
        "alias": "Google Cloud",
        "fullName": "Google Cloud Platform",
        "src": "googlecloud",
        "type": "cloud",
        "area": "server",
        "stack": "back-end",
        "status": null,
        "associated": ["Google"],
        "about": "Plataforma para gerenciamento de dados e arquivos em nuvem.",
        "start": null,
        "advance": null
    },
    {
        "alias": "Heroku",
        "fullName": "Heroku",
        "src": "heroku",
        "type": "cloud",
        "area": "server",
        "stack": "back-end",
        "status": null,
        "associated": ["Heroku"],
        "about": "Plataforma para gerenciamento de dados e arquivos em nuvem.",
        "start": null,
        "advance": null
    },
    {
        "alias": "HTML 5",
        "fullName": "HTML 5",
        "src": "html5",
        "type": "markup-language",
        "area": "web",
        "stack": "front-end",
        "status": "aprofundada",
        "associated": ["HTML"],
        "about": "Linguagem de marcação.",
        "start": "Feb 15 2021",
        "advance": "Jun 30 2021"
    },
    {
        "alias": "IntelliJ",
        "fullName": "IntelliJ IDEA",
        "src": "intellij",
        "type": "software",
        "area": null,
        "stack": null,
        "status": "aprofundada",
        "associated": ["Java","JetBrains"],
        "about": "Ambiente de desenvolvimento integrado (IDE).",
        "start": "Sep 20 2020",
        "advance": "Sep 27 2020"
    },
    {
        "alias": "Ionic",
        "fullName": "Ionic",
        "src": "ionic",
        "type": "framework",
        "area": "mobile",
        "stack": "front-end",
        "status": null,
        "associated": ["JavaScript"],
        "about": "Framework para desenvolvimento de aplicativos móveis.",
        "start": null,
        "advance": null
    },
    {
        "alias": "Java",
        "fullName": "Java",
        "src": "java",
        "type": "programming-language",
        "area": "logic",
        "stack": null,
        "status": "utilizada",
        "associated": ["Java", "Oracle"],
        "about": "Linguagem de programação.",
        "start": "Sep 10 2020",
        "advance": null
    },
    {
        "alias": "JavaScript",
        "fullName": "JavaScript",
        "src": "javascript",
        "type": "programming-language",
        "area": "logic",
        "stack": "full-stack",
        "status": "aprofundada",
        "associated": ["TypeScript"],
        "about": "Linguagem de programação.",
        "start": "Mar 21 2021",
        "advance": "Jun 30 2021"
    },
    {
        "alias": "Jira",
        "fullName": "Jira",
        "src": "jira",
        "type": "software",
        "area": null,
        "stack": null,
        "status": null,
        "associated": ["Trello"],
        "about": "Ferramenta para monitoramento de tarefas e projetos.",
        "start": null,
        "advance": null
    },
    {
        "alias": "jQuery",
        "fullName": "jQuery",
        "src": "jquery",
        "type": "library",
        "area": "web",
        "stack": "front-end",
        "status": null,
        "associated": ["JavaScript"],
        "about": "Biblioteca do JavaScript.",
        "start": null,
        "advance": null
    },
    {
        "alias": "JSON",
        "fullName": "JSON",
        "src": "json",
        "type": "data-interchange-language",
        "area": null,
        "stack": "back-end",
        "status": "aprofundada",
        "associated": ["JavaScript", "XML", "YAML"],
        "about": "Linguagem para intercâmbio de dados.",
        "start": "Jul 18 2021",
        "advance": "Jul 18 2021"
    },
    {
        "alias": "Kotlin",
        "fullName": "Kotlin",
        "src": "kotlin",
        "type": "programming-language",
        "area": "logic",
        "stack": null,
        "status": null,
        "associated": ["JetBrains", "Android"],
        "about": "Linguagem de programação.",
        "start": null,
        "advance": null
    },
    {
        "alias": "LAMP",
        "fullName": "LAMP",
        "src": "lamp",
        "type": "software-compilation",
        "area": "server",
        "stack": "back-end",
        "status": null,
        "associated": ["Linux", "Apache", "MySQL", "MariaDB", "PHP", "Pearl", "Python"],
        "about": "Fornecedor, para Linux, do servidor local para testar e verificar o funcionamento de projetos web.",
        "start": null,
        "advance": null
    },
    {
        "alias": "Laravel",
        "fullName": "Laravel",
        "src": "laravel",
        "type": "framework",
        "area": "web",
        "stack": "full-stack",
        "status": null,
        "associated": ["PHP", "MVC"],
        "about": "Framework full-stack, em PHP, para desenvolvimento web.",
        "start": null,
        "advance": null
    },
    {
        "alias": "Less",
        "fullName": "Less",
        "src": "less",
        "type": "stylesheet-language",
        "area": "web",
        "stack": "front-end",
        "status": "utilizada",
        "associated": ["CSS", "Sass"],
        "about": "Linguagem de folhas de estilo.",
        "start": "Oct 04 2021",
        "advance": null
    },
    {
        "alias": "MAMP",
        "fullName": "MAMP",
        "src": "mamp",
        "type": "software-compilation",
        "area": "server",
        "stack": "back-end",
        "status": null,
        "associated": ["macOS", "Apache", "MySQL", "MariaDB", "PHP", "Pearl", "Python"],
        "about": "Fornecedor, para macOS, do servidor local para testar e verificar o funcionamento de projetos web.",
        "start": null,
        "advance": null
    },
    {
        "alias": "MongoDB",
        "fullName": "MongoDB",
        "src": "mongodb",
        "type": "software",
        "area": "database",
        "stack": "back-end",
        "status": "utilizada",
        "associated": ["SQL"],
        "about": "Software de banco de dados.",
        "start": "Oct 20 2021",
        "advance": null
    },
    {
        "alias": "MySQL",
        "fullName": "MySQL",
        "src": "mysql",
        "type": "software",
        "area": "database",
        "stack": "back-end",
        "status": "utilizada",
        "associated": ["SQL", "Oracle"],
        "about": "Software de banco de dados.",
        "start": "Mar 17 2020",
        "advance": null
    },
    {
        "alias": "NestJS",
        "fullName": "NestJS",
        "src": "nestjs",
        "type": "framework",
        "area": "web",
        "stack": "back-end",
        "status": null,
        "associated": ["JavaScript", "Node.js"],
        "about": "Framework back-end, em JavaScript, para construção de servidores web.",
        "start": null,
        "advance": null
    },
    {
        "alias": "NetBeans",
        "fullName": "NetBeans IDE",
        "src": "netbeans",
        "type": "software",
        "area": null,
        "stack": null,
        "status": "utilizada",
        "associated": ["Java","PHP","Oracle"],
        "about": "Ambiente de desenvolvimento integrado (IDE).",
        "start": "Sep 16 2020",
        "advance": null
    },
    {
        "alias": "Next.js",
        "fullName": "Next.js",
        "src": "nextjs",
        "type": "framework",
        "area": "web",
        "stack": "full-stack",
        "status": null,
        "associated": ["JavaScript","React"],
        "about": "Framework, baseado em React, para desenvolvimento web.",
        "start": null,
        "advance": null
    },
    {
        "alias": "Node.js",
        "fullName": "Node.js",
        "src": "nodejs",
        "type": "software",
        "area": "server",
        "stack": "back-end",
        "status": "aprofundada",
        "associated": ["JavaScript","React"],
        "about": "Software para executar JavaScript fora do navegador.",
        "start": "Mar 21 2021",
        "advance": "Oct 12 2021"
    },
    {
        "alias": "NPM",
        "fullName": "NPM",
        "src": "npm",
        "type": "software",
        "area": "package-manager",
        "stack": null,
        "status": "utilizada",
        "associated": ["Node.js", "Yarn"],
        "about": "Gerenciador de pacotes.",
        "start": "Mar 21 2021",
        "advance": null
    },
    {
        "alias": "Nuxt.js",
        "fullName": "Nuxt.js",
        "src": "nuxtjs",
        "type": "framework",
        "area": "web",
        "stack": "front-end",
        "status": null,
        "associated": ["Vue.js","Node.js"],
        "about": "Framework, baseado em Vue.js, para desenvolvimento web.",
        "start": null,
        "advance": null
    },
    {
        "alias": "Objective-C",
        "fullName": "Objective-C",
        "src": "objectivec",
        "type": "programming-language",
        "area": "logic",
        "stack": null,
        "status": null,
        "associated": ["C","iOS"],
        "about": "Linguagem de programação.",
        "start": null,
        "advance": null
    },
    {
        "alias": "PHP",
        "fullName": "PHP",
        "src": "php",
        "type": "programming-language",
        "area": "logic",
        "stack": null,
        "status": null,
        "associated": ["Laravel","LAMP","MAMP","WAMP","XAMPP"],
        "about": "Linguagem de programação.",
        "start": null,
        "advance": null
    },
    {
        "alias": "PostgreSQL",
        "fullName": "PostgreSQL",
        "src": "postgresql",
        "type": "software",
        "area": "database",
        "stack": "back-end",
        "status": null,
        "associated": ["SQL", "MySQL"],
        "about": "Software de banco de dados.",
        "start": null,
        "advance": null
    },
    {
        "alias": "PyCharm",
        "fullName": "PyCharm",
        "src": "pycharm",
        "type": "software",
        "area": null,
        "stack": null,
        "status": null,
        "associated": ["Python","JetBrains"],
        "about": "Ambiente de desenvolvimento integrado (IDE).",
        "start": null,
        "advance": null
    },
    {
        "alias": "Python",
        "fullName": "Python",
        "src": "python",
        "type": "programming-language",
        "area": "logic",
        "stack": "back-end",
        "status": null,
        "associated": ["Django"],
        "about": "Linguagem de programação.",
        "start": null,
        "advance": null
    },
    {
        "alias": "Rails",
        "fullName": "Rails",
        "src": "rails",
        "type": "framework",
        "area": "web",
        "stack": "back-end",
        "status": null,
        "associated": ["Ruby", "Ruby on Rails", "MVC"],
        "about": "Framework back-end, em Ruby, para desenvolvimento web.",
        "start": null,
        "advance": null
    },
    {
        "alias": "React",
        "fullName": "React",
        "src": "react",
        "type": "library",
        "area": "web",
        "stack": "front-end",
        "status": "utilizada",
        "associated": ["JavaScript","React Native"],
        "about": "Biblioteca do JavaScript para desenvolvimento web.",
        "start": "Apr 05 2021",
        "advance": null
    },
    {
        "alias": "React Native",
        "fullName": "React Native",
        "src": "reactnative",
        "type": "library",
        "area": "mobile",
        "stack": "front-end",
        "status": "utilizada",
        "associated": ["JavaScript","React"],
        "about": "Biblioteca do JavaScript para desenvolvimento mobile.",
        "start": "Apr 05 2021",
        "advance": null
    },
    {
        "alias": "Redux",
        "fullName": "Redux",
        "src": "redux",
        "type": "library",
        "area": "multi-platform",
        "stack": "back-end",
        "status": null,
        "associated": ["JavaScript","React"],
        "about": "Biblioteca do JavaScript para gerenciamento de estados.",
        "start": null,
        "advance": null
    },
    {
        "alias": "Ruby",
        "fullName": "Ruby",
        "src": "ruby",
        "type": "programming-language",
        "area": "logic",
        "stack": null,
        "status": null,
        "associated": ["Rails"],
        "about": "Linguagem de programação.",
        "start": null,
        "advance": null
    },
    {
        "alias": "Sass",
        "fullName": "Sass",
        "src": "sass",
        "type": "stylesheet-language",
        "area": "web",
        "stack": "front-end",
        "status": null,
        "associated": ["CSS", "Less"],
        "about": "Linguagem de folhas de estilo.",
        "start": null,
        "advance": null
    },
    {
        "alias": "Spring",
        "fullName": "Spring Framework",
        "src": "spring",
        "type": "framework",
        "area": "web",
        "stack": null,
        "status": null,
        "associated": ["Java"],
        "about": "Framework, em Java, para desenvolvimento de aplicações.",
        "start": null,
        "advance": null
    },
    {
        "alias": "SQL Server",
        "fullName": "Microsoft SQL Server",
        "src": "sqlserver",
        "type": "software",
        "area": "database",
        "stack": "back-end",
        "status": null,
        "associated": ["SQL", "Microsoft"],
        "about": "Software de banco de dados.",
        "start": null,
        "advance": null
    },
    {
        "alias": "Swift",
        "fullName": "Swift",
        "src": "swift",
        "type": "programming-language",
        "area": "logic",
        "stack": null,
        "status": null,
        "associated": ["iOS", "macOS", "Objective-C"],
        "about": "Linguagem de programação.",
        "start": null,
        "advance": null
    },
    {
        "alias": "Tailwind CSS",
        "fullName": "Tailwind CSS",
        "src": "tailwindcss",
        "type": "framework",
        "area": "web",
        "stack": "front-end",
        "status": null,
        "associated": ["CSS", "Less", "Sass"],
        "about": "Framework CSS para desevolvimento de interfaces.",
        "start": null,
        "advance": null
    },
    {
        "alias": "Trello",
        "fullName": "Trello",
        "src": "trello",
        "type": "software",
        "area": null,
        "stack": null,
        "status": "utilizada",
        "associated": ["Jira"],
        "about": "Ferramenta para monitoramento de tarefas e projetos.",
        "start": "Mar 19 2021",
        "advance": null
    },
    {
        "alias": "TypeScript",
        "fullName": "TypeScript",
        "src": "typescript",
        "type": "programming-language",
        "area": "logic",
        "stack": "full-stack",
        "status": null,
        "associated": ["JavaScript","Microsoft"],
        "about": "Linguagem de programação.",
        "start": null,
        "advance": null
    },
    {
        "alias": "Visual Studio",
        "fullName": "Microsoft Visual Studio",
        "src": "visualstudio",
        "type": "software",
        "area": null,
        "stack": null,
        "status": null,
        "associated": ["C","C++","C#","Microsoft",".NET"],
        "about": "Ambiente de desenvolvimento integrado (IDE).",
        "start": null,
        "advance": null
    },
    {
        "alias": "VS Code",
        "fullName": "Microsoft Visual Studio Code",
        "src": "vscode",
        "type": "text-editor",
        "area": null,
        "stack": null,
        "status": "aprofundada",
        "associated": ["Atom", "Microsoft"],
        "about": "Editor de texto.",
        "start": "Mar 18 2021",
        "advance": "Apr 05 2021"
    },
    {
        "alias": "Vue.js",
        "fullName": "Vue.js",
        "src": "vuejs",
        "type": "framework",
        "area": "web",
        "stack": "front-end",
        "status": null,
        "associated": ["JavaScript","Node.js", "Nuxt.js"],
        "about": "Framework, em JavaScript, para desenvolvimento de interfaces e aplicativos single-page.",
        "start": null,
        "advance": null
    },
    {
        "alias": "WAMP",
        "fullName": "WAMP",
        "src": "wamp",
        "type": "software-compilation",
        "area": "server",
        "stack": "back-end",
        "status": "utilizada",
        "associated": ["Windows", "Apache", "MySQL", "MariaDB", "PHP", "Pearl", "Python"],
        "about": "Fornecedor, para Windows, do servidor local para testar e verificar o funcionamento de projetos web.",
        "start": "Mar 15 2020",
        "advance": null
    },
    {
        "alias": "WordPress",
        "fullName": "WordPress",
        "src": "wordpress",
        "type": "software",
        "area": "web",
        "stack": "back-end",
        "status": null,
        "associated": ["MySQl", "PHP"],
        "about": "Software para criação de sites.",
        "start": null,
        "advance": null
    },
    {
        "alias": "XAMPP",
        "fullName": "XAMPP",
        "src": "xampp",
        "type": "software-compilation",
        "area": "server",
        "stack": "back-end",
        "status": "utilizada",
        "associated": ["Windows", "Apache", "MySQL", "MariaDB", "PHP", "Pearl", "Python"],
        "about": "Fornecedor, multiplataforma, do servidor local para testar e verificar o funcionamento de projetos web.",
        "start": "Mar 15 2020",
        "advance": null
    },
    {
        "alias": "XML",
        "fullName": "XML",
        "src": "xml",
        "type": "data-interchange-language",
        "area": null,
        "stack": "back-end",
        "status": null,
        "associated": ["JSON","YAML"],
        "about": "Linguagem para intercâmbio de dados.",
        "start": null,
        "advance": null
    },
    {
        "alias": "YAML",
        "fullName": "YAML",
        "src": "yaml",
        "type": "data-interchange-language",
        "area": null,
        "stack": "back-end",
        "status": null,
        "associated": ["JSON","XML"],
        "about": "Linguagem para intercâmbio de dados.",
        "start": null,
        "advance": null
    },
    {
        "alias": "Yarn",
        "fullName": "Yarn",
        "src": "yarn",
        "type": "software",
        "area": "package-manager",
        "stack": null,
        "status": "utilizada",
        "associated": ["Node.js", "NPM"],
        "about": "Gerenciador de pacotes.",
        "start": "Mar 22 2021",
        "advance": null
    }
]
